fields:
    creator: ["creator1","creator1"]
    contributor: ["contributor 1", "contributor 2"]
    lang: ["en", "ga"]
    rights: ["rights","This will be a rights statement"]
    publisher: ["your organisation","another publisher"]
    subject: ["stuff", "things"]
    type: ["text", "Social Media Posts"]
    description: ["this is a social media post", "Message from a member of the public"]
    title: ["title1","title2"]
    date: ["date1","date2"]
    format: ["format1","format2"]
    identifier: ["id1","id2"]
    source: ["source1","source2"]
    relation: ["mother","father"]    
    coverage: ["cov1", "cov2"]
